on:
  workflow_dispatch:

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH and Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }} 
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} << EOF
            # Navigate to the project directory dynamically
            cd /home/${USER_NAME}/${PROJECT_NAME}

            # Pull latest changes
            git checkout main
            git fetch --all
            git reset --hard origin/main
            git pull origin main

            # Restore and build the .NET app
            dotnet restore
            dotnet build --configuration Release
            
            # Stop existing app if running
            sudo systemctl stop ${PROJECT_NAME} || true
            
            # Publish the app
            dotnet publish -c Release -o /home/${USER_NAME}/${PROJECT_NAME}/published

            # Restart the service
            sudo systemctl start ${PROJECT_NAME}
          EOF
