on:
  push:
    branches:
      - main # Auto-deploy kapag may push sa main branch

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH and Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} << 'EOF'
            set -e  # Mag-stop kung may error
            
            # Navigate to project directory
            cd ~/Sample-AutoDeploy

            # Ensure correct branch
            git fetch --all
            git reset --hard origin/main
            git pull origin main

            # Ensure .NET SDK is installed
            if ! command -v dotnet &> /dev/null; then
              echo "Installing .NET SDK..."
              wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
              chmod +x dotnet-install.sh
              ./dotnet-install.sh --install-dir /usr/local/share/dotnet
              export PATH=$PATH:/usr/local/share/dotnet
            fi

            # Restore, build, and publish
            dotnet restore
            dotnet build --configuration Release
            dotnet publish -c Release -o ~/Sample-AutoDeploy/published

            # Restart the application
            sudo systemctl daemon-reload
            sudo systemctl restart Sample-AutoDeploy

            echo "✅ Deployment successful!"
          EOF
